### ISSUE TITLE
LocalCUDACluster with protocol="ucx" and enable_tcp_over_ucx=on, blocks cuML CI for now

### ISSUE THREAD

**Issue by dantegd** [rapidsai/dask-cuda#288] opened 2020-05-02 17:35 UTC
Until yesterday morning the following worked fine AFAIK:
```python
    cluster = LocalCUDACluster(protocol="ucx",
                               enable_tcp_over_ucx=True,
                               enable_nvlink=False,
                               enable_infiniband=False,
                               ucx_net_devices="auto")
```

yet last night that started failing in cuML's CI (taken from https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fcuml%2Fprb%2Fcuml-gpu-build/detail/cuml-gpu-build/10137/pipeline/) with: 

```bash
        cluster = LocalCUDACluster(protocol="ucx",
                                   enable_tcp_over_ucx=enable_tcp_over_ucx,
                                   enable_nvlink=enable_nvlink,
                                   enable_infiniband=enable_infiniband,
>                                  ucx_net_devices="auto")

cuml/test/dask/conftest.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/conda/envs/gdf/lib/python3.7/site-packages/dask_cuda/local_cuda_cluster.py:233: in __init__
    self.sync(self._correct_state)
/conda/envs/gdf/lib/python3.7/site-packages/distributed/deploy/cluster.py:163: in sync
    return sync(self.loop, func, *args, **kwargs)
/conda/envs/gdf/lib/python3.7/site-packages/distributed/utils.py:347: in sync
    raise exc.with_traceback(tb)
/conda/envs/gdf/lib/python3.7/site-packages/distributed/utils.py:331: in f
    result[0] = yield future
/conda/envs/gdf/lib/python3.7/site-packages/tornado/gen.py:735: in run
    value = future.result()
/conda/envs/gdf/lib/python3.7/site-packages/distributed/deploy/spec.py:335: in _correct_state_internal
    await w  # for tornado gen.coroutine support
/conda/envs/gdf/lib/python3.7/site-packages/distributed/nanny.py:268: in start
    response = await self.instantiate()
/conda/envs/gdf/lib/python3.7/site-packages/distributed/nanny.py:351: in instantiate
    result = await self.process.start()
/conda/envs/gdf/lib/python3.7/site-packages/distributed/nanny.py:550: in start
    msg = await self._wait_until_connected(uid)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <distributed.nanny.WorkerProcess object at 0x7fa1a42a3690>
uid = 'b2d880ba283c4470a4a030dbb42f8d60'

    async def _wait_until_connected(self, uid):
        delay = 0.05
        while True:
            if self.status != "starting":
                return
            try:
                msg = self.init_result_q.get_nowait()
            except Empty:
                await asyncio.sleep(delay)
                continue
    
            if msg["uid"] != uid:  # ensure that we didn't cross queues
                continue
    
            if "exception" in msg:
                logger.error(
                    "Failed while trying to start worker process: %s", msg["exception"]
                )
                await self.process.join()
>               raise msg
E               TypeError: exceptions must derive from BaseException
```

I tested locally and pretty much the same thing happens, with some added logs that look like: 

```bash 
distributed.utils - ERROR - addresses should be strings or tuples, got None
Traceback (most recent call last):
  File "/home/galahad/miniconda3/envs/ns0502/lib/python3.7/site-packages/distributed/utils.py", line 664, in log_errors
    yield
  File "/home/galahad/miniconda3/envs/ns0502/lib/python3.7/site-packages/distributed/scheduler.py", line 2169, in remove_worker
    address = self.coerce_address(address)
  File "/home/galahad/miniconda3/envs/ns0502/lib/python3.7/site-packages/distributed/scheduler.py", line 4883, in coerce_address
    raise TypeError("addresses should be strings or tuples, got %r" % (addr,))
TypeError: addresses should be strings or tuples, got None
distributed.core - ERROR - addresses should be strings or tuples, got None
Traceback (most recent call last):
  File "/home/galahad/miniconda3/envs/ns0502/lib/python3.7/site-packages/distributed/core.py", line 399, in handle_comm
    result = handler(comm, **msg)
  File "/home/galahad/miniconda3/envs/ns0502/lib/python3.7/site-packages/distributed/scheduler.py", line 2169, in remove_worker
    address = self.coerce_address(address)
  File "/home/galahad/miniconda3/envs/ns0502/lib/python3.7/site-packages/distributed/scheduler.py", line 4883, in coerce_address
    raise TypeError("addresses should be strings or tuples, got %r" % (addr,))
TypeError: addresses should be strings or tuples, got None
```

Here is a list of conda packages in the environmtent: 

<details><summary>Conda and environment details</summary><pre>
     
     ***Environment Variables***
     PATH                            : /usr/local/cuda-10.2/bin:/usr/local/cuda-10.2/NsightCompute-2019.1:/home/galahad/miniconda3/envs/ns0502/bin:/home/galahad/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-10.2/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/galahad/miniconda3/envs/ns0502
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/galahad/miniconda3/condabin/conda
     # packages in environment at /home/galahad/miniconda3/envs/ns0502:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                      1_llvm    conda-forge
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     attrs                     19.3.0                     py_0    conda-forge
     bokeh                     2.0.1            py37hc8dfbb8_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1001    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
     certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.4.1                      py_0    conda-forge
     cmake                     3.14.5               hf94ab9c_0    conda-forge
     cudatoolkit               10.2.89              h6bb024c_0    nvidia
     cudf                      0.14.0a200502         py37_4051    rapidsai-nightly
     cudnn                     7.6.5                cuda10.2_0
     cuml                      0.14.0a0+2168.gddc3be21b          pypi_0    pypi
     cupy                      7.3.0            py37h940342b_0    conda-forge
     curl                      7.69.1               h33f0ec9_0    conda-forge
     cython                    0.29.17          py37h3340039_0    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.15.0+12.g666b53af          pypi_0    pypi
     dask-cuda                 0.14.0a200502           py37_55    rapidsai-nightly
     dask-cudf                 0.14.0a200502         py37_4051    rapidsai-nightly
     distributed               2.15.2+2.gd8f46d50          pypi_0    pypi
     dlpack                    0.2                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     doxygen                   1.8.18               hd1b7508_0    conda-forge
     expat                     2.2.9                he1b5a44_2    conda-forge
     fastavro                  0.23.3           py37h8f50634_0    conda-forge
     fastrlock                 0.4             py37h3340039_1001    conda-forge
     freetype                  2.10.1               he06d7ca_0    conda-forge
     fsspec                    0.7.3                      py_0    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
     importlib_metadata        1.6.0                         0    conda-forge
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     joblib                    0.14.1                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     krb5                      1.17.1               h2fd8d38_0    conda-forge
     ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
     libblas                   3.8.0               16_openblas    conda-forge
     libcblas                  3.8.0               16_openblas    conda-forge
     libcudf                   0.14.0a200502     cuda10.2_4051    rapidsai-nightly
     libcumlprims              0.14.0a200502       cuda10.2_26    rapidsai-nightly
     libcurl                   7.69.1               hf7181ac_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1007    conda-forge
     libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
     libhwloc                  2.1.0                h3c4fd83_0    conda-forge
     libiconv                  1.15              h516909a_1006    conda-forge
     liblapack                 3.8.0               16_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnvstrings              0.14.0a200502     cuda10.2_4051    rapidsai-nightly
     libopenblas               0.3.9                h5ec1e0e_0    conda-forge
     libpng                    1.6.37               hed695b0_1    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.14.0a200502      cuda10.2_287    rapidsai-nightly
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libuv                     1.34.0               h516909a_0    conda-forge
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvm-openmp               10.0.0               hc9558a2_0    conda-forge
     llvmlite                  0.31.0           py37h5202443_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markupsafe                1.1.1            py37h8f50634_1    conda-forge
     more-itertools            8.2.0                      py_0    conda-forge
     msgpack-python            1.0.0            py37h99015e2_1    conda-forge
     nccl                      2.6.4.1              hc6a2c23_0    conda-forge
     ncurses                   6.1               hf484d3e_1002    conda-forge
     numba                     0.48.0           py37hb3f55d8_0    conda-forge
     numpy                     1.18.1           py37h8960a57_1    conda-forge
     nvstrings                 0.14.0a200502         py37_4051    rapidsai-nightly
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1g               h516909a_0    conda-forge
     packaging                 20.1                       py_0    conda-forge
     pandas                    0.25.3           py37hb3f55d8_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pillow                    7.1.2            py37h718be6c_0    conda-forge
     pip                       20.1               pyh9f0ad1d_0    conda-forge
     pluggy                    0.13.0                   py37_0    conda-forge
     protobuf                  3.8.0            py37he1b5a44_2    conda-forge
     psutil                    5.7.0            py37h8f50634_1    conda-forge
     py                        1.8.1                      py_0    conda-forge
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     pynvml                    8.0.4                      py_0    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pytest                    5.4.1            py37hc8dfbb8_0    conda-forge
     pytest-timeout            1.3.4                      py_0    conda-forge
     python                    3.7.6           h8356626_5_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.1             pyh9f0ad1d_0    conda-forge
     pyyaml                    5.3.1            py37h8f50634_0    conda-forge
     re2                       2020.05.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.14.0a200502          py37_287    rapidsai-nightly
     scikit-learn              0.22.2.post1     py37hcdab131_0    conda-forge
     scipy                     1.4.1            py37ha3d9a3c_3    conda-forge
     setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
     six                       1.14.0                     py_1    conda-forge
     snappy                    1.1.8                he1b5a44_1    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     statsmodels               0.11.1           py37h8f50634_1    conda-forge
     tbb                       2020.1               hc9558a2_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.4            py37h8f50634_1    conda-forge
     typing_extensions         3.7.4.1          py37hc8dfbb8_3    conda-forge
     ucx                       1.8.0+g5a306c1      cuda10.2_15    rapidsai-nightly
     ucx-py                    0.14.0a0+194.ga53adb3          pypi_0    pypi
     umap-learn                0.4.2            py37hc8dfbb8_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
     wheel                     0.34.2                     py_1    conda-forge
     xz                        5.2.5                h516909a_0    conda-forge
     yaml                      0.2.4                h516909a_0    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.1.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge
     
</pre></details>

**Comment by pentschev** [comment] 2020-05-02 18:37
Thanks for the report @dantegd , is that reproducible in a DGX or workstation as well?

**Comment by dantegd** [comment] 2020-05-02 21:56
@pentschev it should be, but I haven't been able to try it since I couldn't access one in in the weekend. i did try in a machine with 4xt4, one with 2xv100 and one with 1x2070S and it happened just the same. 

Note that the dask used by cuml (both in CI and the developer conda environments) is built from source: 
```bash
dask                      2.15.0+12.g666b53af          pypi_0    pypi
distributed               2.15.2+2.gd8f46d50          pypi_0    pypi
```

after your question I went ahead and installed the 2.15 released `dask`, `dask-core` and `distributed` (without modifying `dask-cuda`, `ucx` or `ucx-py`) from conda, with that package the issue doesn't occur. So my best guess is that a merge to either of those happened on Friday that broke things for `dask-cuda` with `ucx` and the options I posted.

**Comment by quasiben** [comment] 2020-05-03 21:24
I suspect the issue comes from a recently merged PR: https://github.com/rapidsai/dask-cuda/pull/286

Probably setting `ucx_net_device=None` or not setting it at all should resolve the issue.  You probably don't need this flag set to anything as you are not using an InfiniBand devices

**Comment by pentschev** [comment] 2020-05-03 21:24
Thanks @dantegd for doing that test, that's helpful to know. I don't really think this could be the cause, but could you try reverting https://github.com/dask/distributed/pull/3759 and checking if that's the cause? AFAIK, this has been the only recent change that affects UCX in Dask, but it's not anything that should change the default behavior.

I can try to take a look at this during the week as well.

**Comment by pentschev** [comment] 2020-05-03 22:02
> I suspect the issue comes from a recently merged PR: #286

I don't think that's true for a few reasons:

1. No behavior has changed in that PR;
1. It seems that reverting dask/dask-core/distributed has solved the issue.

> Probably setting ucx_net_device=None or not setting it at all should resolve the issue. You probably don't need this flag set to anything as you are not using an InfiniBand devices

This is a good point though, `ucx_net_devices` is only useful if you have IB devices available _and_ in a useful state (meaning they have to be configured properly): https://github.com/rapidsai/dask-cuda/blob/branch-0.14/dask_cuda/local_cuda_cluster.py#L86-L98 .

Regardless, I filed https://github.com/rapidsai/dask-cuda/issues/289 to make potentially unsupported usage of `ucx_net_devices="auto"` more resilient/verbose.

**Comment by pentschev** [comment] 2020-07-13 16:28
@dantegd could you give us an update on whether this is still an issue?

**Comment by pentschev** [comment] 2020-11-30 13:14
I believe this has been fixed, closing for now.

**Closed by pentschev** 2020-11-30 13:14 UTC
