### ISSUE TITLE
Difficulty running distributed CuPy on Summit

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cuda#127] opened 2019-09-02 19:11 UTC
(There isn't a great repository for these kinds of things, so I'm using this one, because it seems the least inappropriate).

I'm trying to run a small distributed GPU computation on Summit with CuPy.

### Environment setup

I'm on the following branches:

-  https://github.com/mrocklin/dask-jobqueue@spec-rewrite
-  https://github.com/dask/distributed@master

I run `dask-scheduler` on a login node

```
$ dask-scheduler --interface ib0
distributed.scheduler - INFO -   Scheduler at:     tcp://10.41.0.31:8786
```

I then submit a script a few times to launch a few dask workers

```bash
#!/usr/bin/env bash

#BSUB -J dask-worker
#BSUB -P GEN119
#BSUB -W 00:30
#BSUB -nnodes 1
JOB_ID=${LSB_JOBID%.*}

module load cuda/10.1.168

/ccs/home/mrocklin/anaconda/envs/dev/bin/python -m dask_cuda.dask_cuda_worker \
    tcp://10.41.0.31:8786 \
    --death-timeout 60 \
    --interface ib0
```

### Running things from Python

I then connect to this cluster, wait for the workers to arrive, and run the following computation which creates and sums a modest GPU array with CuPy.

```python
from dask.distributed import Client
client = Client('tcp://10.41.0.31:8786')

import dask.array as da
import cupy
rs = da.random.RandomState(RandomState=cupy.random.RandomState)
x = rs.random((100000, 100000))
x.sum().compute()
```

```python-traceback
/autofs/nccs-svm1_home1/mrocklin/distributed/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1672                             exc = CancelledError(key)
   1673                         else:
-> 1674                             six.reraise(type(exception), exception, traceback)
   1675                         raise exc
   1676                     if errors == "skip":

~/anaconda/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/autofs/nccs-svm1_home1/mrocklin/dask/dask/array/random.py in _apply_random()
    453     if RandomState is None:
    454         RandomState = np.random.RandomState
--> 455     state = RandomState(state_data)
    456     func = getattr(state, funcname)
    457     return func(*args, size=size, **kwargs)

/autofs/nccs-svm1_home1/mrocklin/cupy/cupy/random/generator.py in __init__()
     49
     50     def __init__(self, seed=None, method=curand.CURAND_RNG_PSEUDO_DEFAULT):
---> 51         self._generator = curand.createGenerator(method)
     52         self.seed(seed)
     53

/autofs/nccs-svm1_home1/mrocklin/cupy/cupy/cuda/curand.pyx in cupy.cuda.curand.createGenerator()
     91 ###############################################################################
     92
---> 93 cpdef size_t createGenerator(int rng_type) except? 0:
     94     cdef Generator generator
     95     with nogil:

/autofs/nccs-svm1_home1/mrocklin/cupy/cupy/cuda/curand.pyx in cupy.cuda.curand.createGenerator()
     95     with nogil:
     96         status = curandCreateGenerator(&generator, <RngType>rng_type)
---> 97     check_status(status)
     98     return <size_t>generator
     99

/autofs/nccs-svm1_home1/mrocklin/cupy/cupy/cuda/curand.pyx in cupy.cuda.curand.check_status()
     84 cpdef inline check_status(int status):
     85     if status != 0:
---> 86         raise CURANDError(status)
     87
     88

CURANDError: CURAND_STATUS_INITIALIZATION_FAILED
```

I don't have a strong sense for what this error means. 

### Installing CuPy

Historically when I've run into things like this it has been due to a CUDA version mismatch error?   If so, here is how I compiled cupy.

```
module load gcc/6.4.0
module load cuda/10.1.168
git clone https://github.com/cupy/cupy
cd cupy/
pip install -e .
```

**Comment by pentschev** [comment] 2019-09-02 19:27
@mrocklin what version of CuPy did you use? Looks like you're probably on its master branch, is that right?

In general, I'd say CUDA version mismatch is a very likely reason, but there could be a bug in upstream as well. Does the stable release work for you? You can install it with `pip install cupy-cuda100`, that's the precompiled release (unlike the `cupy` pip package), so it won't take long to install.

**Comment by mrocklin** [comment] 2019-09-02 19:29
Summit is on the Power architecture, so the pre-compiled binaries don't work.  

For background you might find the following interesting (although not at all required to deal with this issue) https://blog.dask.org/2019/08/28/dask-on-summit

**Comment by pentschev** [comment] 2019-09-02 19:37
Hmm, I see. If you're using CuPy's master branch, would you mind trying the latest stable (6.3.0), or even better, 6.2.0, which I've used extensively in the past? I think this will help us eliminate potential bugs with upstream (that I haven't tested at all lately).

**Comment by mrocklin** [comment] 2019-09-02 20:57
I just tried 6.3.0 with no luck.  Recompiling now with 6.2.0

**Comment by mrocklin** [comment] 2019-09-04 21:22
I was talking with @benjha and he suggested adding this directive to the LSF script

```bash
#BSUB -alloc_flags gpumps
```

https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide/

**Comment by mrocklin** [comment] 2019-09-05 19:29
@benjha worked on the following job script

```bash
#!/usr/bin/env bash

#BSUB -J dask-worker
#BSUB -P STF011
#BSUB -W 1:00
#BSUB -alloc_flags "gpumps"
#BSUB -nnodes 1
JOB_ID=${LSB_JOBID%.*}

jsrun -c 7 -g 6 -n 1 -a 1 python -m distributed.cli.dask_worker --scheduler-file /gpfs/alpine/proj-shared/gen119/benjha/my-scheduler.json --nthreads 1  --memory-limit 80GB  --nanny --death-timeout 60 --interface ib0 --local-directory $MEMBERWORK/gen119 &
```

**Comment by pentschev** [comment] 2019-09-06 08:21
Did this work @mrocklin ? And more importantly if it did, why is this necessary for CuPy to work on Power?

**Comment by mrocklin** [comment] 2019-09-06 14:45
We got cudf to work but didn't try cupy yet.  

> And more importantly if it did, why is this necessary for CuPy to work on Power?

The problem isn't necessarily Power architecture, but maybe other policies within Summit, or the way I built things.  Anyway, this probably isn't something for you to think about personally near term.

**Comment by benjha** [comment] 2019-09-06 22:45
@pentschev 

We like to understand how dask_cuda uses nthreads and nprocs to  map processes and threads to GPUs available, then we can expose resources accordingly with jsrun.

Discarding the jsrun call,   what we want is to have one process per node, 6 threads, each thread sending work to each GPU. Then, how adding more threads per GPUs works.

**Comment by pentschev** [comment] 2019-09-25 10:39
I found out what the issue is, it's not related to CuPy but how Summit nodes work. By default, all GPUs in Summit are set to "Exclusive Process" mode and dask-cuda needs a process per GPU, plus the Client creates another process that needs access to the first GPU. The client process then can't get access to the GPU and errors out in the first attempt to access the GPU.

According to the [Summit docs on MPS](https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide/#mps), we should be able to allow multiple processes per GPU. I tried that but it didn't have any effect. The mode a GPU is set can be checked via `nvidia-smi`, either a "Default" mode (multiple processes permitted):

```
|   0  Quadro GV100        Off  | 00000000:15:00.0 Off |                  Off |
| 34%   47C    P2    38W / 250W |    317MiB / 32478MiB |      0%      Default |
```

or "E. Process" (Exclusive Process):

```
|   0  Quadro GV100        Off  | 00000000:15:00.0 Off |                  Off |
| 34%   47C    P2    38W / 250W |    317MiB / 32478MiB |      0%   E. Process |
```

A simpler way to reproduce the issue (without Dask) is to run two python processes on the same GPU and try to allocate a random array with CuPy in each:

`CUDA_VISIBLE_DEVICES=0 python`

```python
import cupy
a = cupy.random.random(1000)
```

I was able to reproduce the exact same error on my x86 workstation when setting the GPU to "Exclusive Process" mode.

@benjha is there someone who could help us identifying why `-alloc_flags "gpumps"` seem to have no effect? I tried following similar steps to the screencast (with an interactive shell), but no success as well.

**Comment by pentschev** [comment] 2019-09-26 16:41
Indeed, I was on the batch node when running python. I can confirm that launching with `jsrun` solves this for me.

For future reference, to ensure GPU support works with Dask on Summit, it's mandatory to:

1. Pass `-alloc-flags gpumps` to `bsub`; and
2. Once in the launch node, use `jsrun` to start Dask scheduler/workers on compute node(s).

I think the general topic of this issue has been clarified, therefore I'm closing this issue. Feel free to reopen if more clarification is necessary.

**Closed by pentschev** 2019-09-26 16:41 UTC
