### ISSUE TITLE
ValueError: 'ib0' is not a valid network interface.

### ISSUE THREAD

**Issue by ntaherkhani** [rapidsai/dask-cuda#394] opened 2020-08-28 13:53 UTC
Hi,

I followed the setting for a single node and localcudacluster from https://dask-cuda.readthedocs.io/en/latest/ucx.html#starting-a-local-cluster-single-node-only
but I am getting ValueError: 'ib0' is not a valid network interface. Valid network interfaces are: ['lo', 'team1', 'team0', 'virbr0', 'docker0', 'enp96s0f0', 'enp96s0f1', 'enp129s0f0', 'enp129s0f1', 'virbr0-nic']
I removed the interface from my settings  to just use default value but I got ValueError: interface 'enp96s0f0' doesn't have an IPv4 address
I am using rapidsai docker container and IPv6 does not set for docker in daemon.json. I can only use IPV4 . which interface should be set to be able to use UCX as the protocol of localcudacluster single node?

If I  set IPV6 for docker, do I still get the "ValueError: 'ib0' is not a valid network interface." because it is not in list of valid interfaces (['lo', 'team1', 'team0', 'virbr0', 'docker0', 'enp96s0f0', 'enp96s0f1', 'enp129s0f0', 'enp129s0f1', 'virbr0-nic']) ?

I installed UCX-py by following command:
conda create -n ucx -c conda-forge -c rapidsai   cudatoolkit=10.2 ucx-proc=*=gpu ucx ucx-py python=3.6

thanks.

**Comment by jakirkham** [comment] 2020-08-28 16:13
As of RAPIDS 0.15, IB is not built in the UCX packages as we have found that getting this to work correctly depends on linking against the exact OFED version on the system one deploys to. Since we don't know how to do that in a general way and the errors that are caused by doing this incorrectly can be quite difficult to isolate and debug, we thought the safest thing to do was to disable it. We are still investigating how we might improve the deployment story in the future.

For now, would recommend building UCX and UCX-Py from source on the system that you are deploying to. Details on how to do this can be found [here]( https://ucx-py.readthedocs.io/en/latest/install.html#ucx-ofed ).

**Comment by pentschev** [comment] 2020-11-30 13:01
I think the original question has been answered, I'm tentatively closing this, @ntaherkhani feel free to reopen if you're still experiencing issues.

**Closed by pentschev** 2020-11-30 13:01 UTC
