### ISSUE TITLE
[QST] Why am I getting low process memory limit warnings w/ a LocalCUDACluster?

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#1073] opened 2023-01-04 19:23 UTC
Using cudf as the DataFrame backend:
`dask.config.set({"dataframe.backend": "cudf"})`

I started getting repeating warnings-
```
2023-01-04 11:10:35,533 - distributed.worker - WARNING - Managed memory (2.28 GiB) exceeds process memory (1.36 GiB); this will cause premature spilling as well as malfunctions in several heuristic
s. Please ensure that sizeof() returns accurate outputs for your data. Read more: https://distributed.dask.org/en/stable/worker-memory.html
```

This is on a box w/ 512gb of RAM, and I'm starting only 8 workers via fairly simple LocalCUDACluster:
```
LocalCUDACluster(
        protocol="ucx",
        jit_unspill=True,
        rmm_pool_size=pool_size,
        device_memory_limit=device_memory_limit,
        local_directory="/raid/dask-local-dir",
    )
```

Why would workers be created w/ such low system memory limits by default?

```
conda list | grep dask
dask                      2022.12.1+16.gf721de65f          pypi_0    pypi
dask-cuda                 22.12.0            pyhd8ed1ab_0    conda-forge
dask-cudf                 23.2.0a0+214.gc1d8fde9d2          pypi_0    pypi

conda list | grep distributed
distributed               2022.12.1+21.g9d8e18c8          pypi_0    pypi
```

**Comment by pentschev** [comment] 2023-01-04 19:31
I can confirm this with Dask-CUDA benchmarks on a DGX-1 running:

```
python dask_cuda/benchmarks/local_cudf_merge.py -d 0,1,2,3,4,5,6,7 --runs 5 -c 100_000_000
```

**Comment by madsbk** [comment] 2023-01-04 20:28
Yeah, I also just discovered the issue. It is because of a new warning in Distributed: https://github.com/dask/distributed/pull/7450

**Comment by pentschev** [comment] 2023-01-04 20:43
Thanks Mads for the investigation/fix and linking that here! 🙂

**Comment by pentschev** [comment] 2023-01-06 14:09
https://github.com/dask/distributed/pull/7450 is now merged and I don't see the warnings anymore running the same as in https://github.com/rapidsai/dask-cuda/issues/1073#issuecomment-1371334573. Please let us know if you still see this @randerzander .

**Closed by pentschev** 2023-01-06 14:09 UTC
