### ISSUE TITLE
TypeError: 'buffers' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/dask-cuda#467] opened 2020-12-05 01:14 UTC
Using rapids 0.14, conda, Ubuntu 16 or 18, 1 or 2 GPUs.

https://github.com/dask/distributed/issues/4314#issuecomment-739096402

Spent too much time debugging some basic dask stuff, and ended up 2 issues:

1) It seems distributed/dask/dask_cuda keep a "storage" folder where run, and any later cluster (using CLI or local client) will pick up those old files and start to process them.  This seems like bad idea, at minimum the files should be hashed for given client-server instance so they aren't picked up arbitrarily later.  I can work-around by nuking them myself, but that shouldn't have been needed.  Oddly, only the *cuda* client (cluster from CLI or LocalCUDACluster) has an problem, not the normal dask one, so I assume it's something dask_cuda is doing, but I can't be sure.

2) dask_cuda or distributed, again I can't quite tell, is sometimes calling pickle with buffers kwarg, seemingly when I use a large amount of data.  In normal install of rapids-conda, the normal pickle imported in distributed cannot support buffers.  I was told I could install protocol5 experimental package, but I presume rapids/distributed don't depend upon this, but it seems they do.  The full package solution with rapids/dask/distibuted doesn't install protocol5 for example as a dependency.

So I have work-around for Issue 1 but not Issue 2.  I don't understand why dask_cuda would use protocol5 methods if no such support, or why it is even required since protocol4 handles big data.  And the file involved is only 88MB.  If buffering is ever required, that dependency needs to be explicitly added.  Note that by default, only python 3.8 has protocol 5 support.

I did try pip install pickle5 (or conda install -c conda_forge pickle5) and changed `/home/jon/minicondadai/lib/python3.6/site-packages/distributed/protocol/pickle.py` to `import pickle5 as pickle` but still hit other errors.

Here is repro:

1)  Here is the contents of storage.  Put this into folder where one will run, should end up with new folder "storage" with a funny "from_pandas" file in it.

https://0xdata-public.s3.amazonaws.com/jon/storage.zip

2) Then run:

```
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
def main(client):
    pass

import time
if __name__ == '__main__':
    with LocalCUDACluster() as cluster:
        time.sleep(1)
        with Client(cluster) as client:
            time.sleep(1)
            main(client)
```

See how existing "storage" stuff is touched/used and frames are processed, even though the above never does anything with data frames.  This also shows the error regarding buffers.

Originally the data *was* large, so I can imagine dask_cuda is using some techniques, but it does *not* function on default rapids install.

Thanks!

**Comment by jakirkham** [comment] 2020-12-05 01:27
A [quick search through this repo]( https://github.com/rapidsai/dask-cuda/search?q=buffers ) shows no such argument. So I don't think there is a Dask-CUDA bug.

**Comment by pseudotensor** [comment] 2020-12-05 01:32
> A [quick search through this repo](https://github.com/rapidsai/dask-cuda/search?q=buffers) shows no such argument. So I don't think there is a Dask-CUDA bug.

Thanks, what about the "storage" thing?

**Comment by pseudotensor** [comment] 2020-12-05 07:20
I can close for the "storage" issue with above solution, but not for the buffers issue.  pickle.loads buffers is clearly from distributed, but that is where failure is.  Question is who writes to "storage" folder with pickle-like files that have buffers later read by distributed.

**Comment by pentschev** [comment] 2020-12-07 10:21
I believe the issue with storage is a duplicate of https://github.com/rapidsai/dask-cuda/issues/265 .

As for pickling issues, I understand you're still on Python 3.6 and that's why you're trying RAPIDS 0.14, but notice that it's older than our current legacy -- 0.15, which will be replaced by 0.16 when 0.17 is released by the end of the week -- and we don't really have the resources to support these much older versions, so it would certainly be much easier for us to help you if you were on a more recent version of RAPIDS. It's also important to keep in mind that we generally don't pin third-party library versions (unless we know of an issue at release time), thus it's also common for such libraries to release non-backwards compatible changes that may break, so it's possible that even if you manage to find a version of Dask that was compatible with RAPIDS 0.14 you'll still have to find compatible versions of third-party libraries.

**Comment by pseudotensor** [comment] 2020-12-07 18:26
265 is dup of storage issue yes, but not of the buffers one.

On age of rapids, I'm curious how things work.  I don't see why rapids 0.14 would be using pickle5 related dumping if python 3.6 and distributed don't support it.  I'm curious because I'll be updating to rapids 0.16 soon and will likely encounter the same problem if no one knows why rapids 0.14 was using protocol5 like pickle behavior that makes dask fail.

e.g. later versions of distributed can import pickle5, so maybe that would work. However, that would not be OOTB since pickle5 is experiment package not installed by default.  Only python 3.8 supports pickle5 OOTB, so then rapids 0.16 or 0.17 would not work on python 3.7 for bigger data (or however I encountered it and however rapids 0.14 reached that state).

**Comment by pentschev** [comment] 2020-12-07 19:08
As I said, RAPIDS generally doesn't pin versions of packages, including of Dask and Distributed. Pickling is also handled by Distributed and IIRC, RAPIDS doesn't do any pickling of its own, therefore, what you seeing is probably due to a version of Distributed that is incompatible with RAPIDS 0.14, probably a newer one.

**Comment by pseudotensor** [comment] 2020-12-07 22:50
dask_cudf does do pickling and manages this in the "storage" folder:

https://github.com/rapidsai/dask-cuda/search?q=pickle

E.g. see pickle.dumps etc.

**Comment by pseudotensor** [comment] 2020-12-07 22:51
Maybe @jakirkham has thoughts since he worked on the spilling stuff last.

**Comment by jakirkham** [comment] 2020-12-08 02:30
Going to close this out. Let's keep the discussion in issue ( https://github.com/dask/distributed/issues/4314 ).

**Closed by jakirkham** 2020-12-08 02:30 UTC
