### ISSUE TITLE
[BUG] Can't start dask-cuda-worker with --enable_nvlink without scheduler.json file

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#240] opened 2020-02-20 02:36 UTC
If I start the dask-scheduler:
```
dask-scheduler --protocol ucx
```

And then:
```
dask-cuda-worker --enable_nvlink --host randy-0:8786
```

I get errors about the address already being in use (nothing else is already using the port):
```
tornado.application - ERROR - Multiple exceptions in yield list                                                                                                         
Traceback (most recent call last):                                                                                                                                      
  File "/home/rgelhau/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback                                                              
    result_list.append(f.result())                                                                                                                                      
  File "/home/rgelhau/conda/envs/rapids/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable                                                                   
    return (yield from awaitable.__await__())                                                                                                                           
  File "/home/rgelhau/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 238, in start                                                           
    await self.listen(self._start_address, listen_args=self.listen_args)                                                                                                
  File "/home/rgelhau/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 321, in listen                                                           
    await listener.start()                                                                                                                                              
  File "/home/rgelhau/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/tcp.py", line 411, in start                                                        
    self.port, address=self.ip, backlog=backlog                                                                                                                         
  File "/home/rgelhau/conda/envs/rapids/lib/python3.7/site-packages/tornado/netutil.py", line 174, in bind_sockets                                                      
    sock.bind(sockaddr)                                                                                                                                                 
OSError: [Errno 98] Address already in use    
```

But if I start the scheduler and have it write to a scheduler.json file and connect with it, everything works:
```
dask-scheduler --protocol ucx --scheduler-file sched.json

# works
dask-cuda-worker --enable_nvlink --scheduler-file sched.json
```

**Comment by randerzander** [comment] 2020-02-20 02:44
This may be something related to resolving the hostname. I notice that the sched.json includes the scheduler's IP address, not a hostname.

If I edit sched.json and replace it with the scheduler's hostname, the dask-cuda-worker processes fail with the same error.

**Comment by quasiben** [comment] 2020-02-20 03:34
When you define the host can you try with the protocol defined as well:

> dask-cuda-worker --enable_nvlink --host ucx://randy-0:8786

**Comment by pentschev** [comment] 2020-02-20 11:47
@quasiben is correct, if you only pass `host:port` then `tcp://host:port` is implied, therefore you need to specify `ucx://host:port`.

**Comment by randerzander** [comment] 2020-02-20 14:24
```
dask-cuda-worker --local-directory /tmp --enable_nvlink --host ucx://randy-0:8786
```
fails with the same "OSError: [Errno 98] Address already in use" message.

Does it look like I'm missing any packages? My environment:
```
channels:
  - rapidsai-nightly
  - nvidia
  - conda-forge
  - blazingsql-nightly
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - cudf=0.13
  - dask-cuda
  - dask-cudf
  - cuml
  - ucx-py
  - ucx-proc=*=gpu
  - blazingsql
  - scipy
  - scikit-learn
  - cupy=7.0
  - gspread
  - oauth2client
```

**Comment by pentschev** [comment] 2020-03-05 00:08
Just a quick update here, @randerzander and I verified that this is only an issue when using the hostname rather than the IP address (such as `ucx://randy-0:8786` above). I filed https://github.com/rapidsai/ucx-py/issues/430, as this seems to be an issue on the UCX-Py side.

**Comment by jakirkham** [comment] 2020-03-06 14:27
I believe this was fixed by PR ( https://github.com/rapidsai/ucx-py/pull/431 ). Could you please retest 🙂

**Comment by pentschev** [comment] 2020-05-05 21:59
I can confirm running as below works now, note that the `ucx://` is required otherwise it implies `tcp://`.

```
# scheduler running on host `dgx12`
dask-scheduler --protocol

# dask-cuda-worker running on host `dgx12` or `dgx13`
dask-cuda-worker ucx://dgx12:8786 --enable-nvlink
```

Closing this, but feel free to reopen if there are still any issues.

**Closed by pentschev** 2020-05-05 21:59 UTC
