### ISSUE TITLE
[BUG] Attribute 'protocol' not found in LocalCUDACluster in 0.7

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/dask-cuda#54] opened 2019-05-16 22:36 UTC
When running the very common

```
from dask_cuda import LocalCUDACluster

cluster = LocalCUDACluster()
```

I get the error 
```
AttributeError: 'LocalCUDACluster' object has no attribute 'protocol'
```

This call is used throughout many existing and upcoming notebooks.  Can someone please help fix this?  Thanks!

**Comment by pentschev** [comment] 2019-05-17 08:04
Can you confirm what versions of dask, distributed and dask-cuda you have installed?

I just did a clean conda install of RAPIDS 0.7, then installed dask and dask-cuda with conda as well and can't reproduce that issue.

For reference, I have:

```
dask                      1.2.2                      py_0  
dask-core                 1.2.2                      py_0  
dask-cuda                 0.7.0                    py37_0    rapidsai
distributed               1.28.1                   py37_0  
```

**Comment by mrocklin** [comment] 2019-05-17 12:39
@taureandyernv is it possible that you're on distributed master?  There are several changes in the next version that might affect you if so.

**Comment by taureandyernv** [comment] 2019-05-17 15:52
@pentschev , I use only the nightly docker containers, so I should be as up to date as one can be.  @mrocklin when is the next version coming out?  Right now, 5 notebooks are affected, and we do want to start switching over to `dask_x` soon, as well as get solid tutorials, to get on target for 0.8 :)

**Comment by mrocklin** [comment] 2019-05-17 16:13
To be clear, I'm checking to make sure that you *aren't* on `distributed` master, which would likely break dask-cuda.  

If the latest release of distributed breaks dask-cuda then we'll have to push out a small release for `dask-cuda`.

**Comment by pentschev** [comment] 2019-05-17 17:34
I agree with @mrocklin, it's fine to use nightly RAPIDS docker containers, but they should always point to dask and distributed releases, never (hopefully) to master.

**Comment by pentschev** [comment] 2019-05-17 17:54
@taureandyernv I tried the nightly docker build now, still can't reproduce. If it's still an issue, could you double-check you're on the latest nightly build and post here the output from `conda info`?

**Comment by pentschev** [comment] 2019-06-18 21:10
This has been solved some weeks ago. I'm closing it, but feel free to reopen if you see something related to that.

**Closed by pentschev** 2019-06-18 21:10 UTC

**Comment by taureandyernv** [comment] 2019-06-18 21:29
@pentschev , thanks for the assist, buddy, but the issue i had was `cannot import name 'SpecCluster'`.  @mrocklin says its fixed but not yet released in dask.distributed.  We just have to wait :)  You were close though!

**Comment by mrocklin** [comment] 2019-06-18 21:43
I think that this is also what @pentschev was saying in our recent meeting.  dask-cuda master currently depends on distributed master.  We're trying to get distributed out in the next few days, until then I recommend using git master if possible.
