### ISSUE TITLE
[BUG] dask-cudf series on computing returns `FrameProxyObject` instead of `cudf.core.series.Series` with jit_unspill

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/dask-cuda#727] opened 2021-09-17 22:46 UTC
###  dask-cudf series on computing returns `proxify_device_objects.FrameProxyObject`

We seem to be returning `proxify_device_objects.FrameProxyObject`  instead of series when calling compute. 

```python
import dask_cudf
import cudf
from dask_cuda import LocalCUDACluster
from dask.distributed import Client

cluster = LocalCUDACluster(jit_unspill=True,CUDA_VISIBLE_DEVICES=['0'])
client = Client(cluster)
```

```
cudf_df = cudf.DataFrame({'a':[1,2,3]})
df = dask_cudf.from_cudf(cudf_df,npartitions=2)
print(type(df['a'].compute()))
```

```python
<class 'dask_cuda.proxify_device_objects.FrameProxyObject'>
```

#### Expected Output (What we get with `jit_unspill=False`. 

```python

cluster = LocalCUDACluster(jit_unspill=False,CUDA_VISIBLE_DEVICES=['0'])
client = Client(cluster)

cudf_df = cudf.DataFrame({'a':[1,2,3]})
df = dask_cudf.from_cudf(cudf_df,npartitions=2)
print(type(df['a'].compute()))
<class 'cudf.core.series.Series'>
```

#### Env:
```
# packages in environment at /nvme/0/vjawa/conda/envs/rapids-21.10-sep-17-dask-sql-gpu-bdb:
dask                      2021.9.0+17.gdc7ad4ae          pypi_0    pypi
dask-cuda                 21.10.0a0+40.gaf0e678           dev_0    <develop>
dask-sql                  0.3.10.dev36+gcb0b3fe          pypi_0    pypi

cudf                      21.10.00a210917 cuda_11.2_py38_g156d5b5e5d_309    rapidsai-nightly
dask-cudf                 21.10.00a210917 py38_g156d5b5e5d_309    rapidsai-nightly
libcudf                   21.10.00a210917 cuda11.2_g156d5b5e5d_309    rapidsai-nightly
```

**Comment by madsbk** [comment] 2021-09-20 06:37
This is by design. Using jit-unspill has the (sometimes) undesirable side effect that `ProxyObjects` are _leaked_ to the tasks and client. 
It is possible to use `DASK_JIT_UNSPILL_COMPATIBILITY_MODE=1` to avoid this but then you don't get the full performance effect of jit-unspill.

Having said that, if _leaking_ `ProxyObjects` to the client is a particular problem, we could monkey patch Distributed to automatically un-proxify compute outputs.

**Comment by VibhuJawa** [comment] 2021-09-20 22:46
> This is by design. Using jit-unspill has the (sometimes) undesirable side effect that ProxyObjects are leaked to the tasks and client.

Thanks for the explanation. 

> Having said that, if leaking ProxyObjects to the client is a particular problem, we could monkey patch Distributed to automatically un-proxify compute outputs.

I am not sure if they are a problem per say but can be confusing for users. FWIW, Computing series  is an active pattern people do to single GPU work .  I don't think that fixing/patching this should be a priority.  


Also, CC: @randerzander , @beckernick  and @ayushdg  to weigh in.

**Comment by pentschev** [comment] 2022-05-19 16:18
I believe this may have been fixed or in agreement that this won't be fixed and could be closed, could you confirm @VibhuJawa @madsbk ?

**Comment by VibhuJawa** [comment] 2022-05-19 23:08
> I believe this may have been fixed or in agreement that this won't be fixed and could be closed, could you confirm @VibhuJawa @madsbk ?

I agee that we are in agreement that we wont fix this for now. Lets re-open if the need arises.

**Closed** 2022-05-19 23:56 UTC

**Comment by jakirkham** [comment] 2022-05-19 23:59
It's worth noting that there's some exploration of moving this spilling logic into cuDF itself ( https://github.com/rapidsai/cudf/pull/10746 )
