### ISSUE TITLE
Overly precise `click==8.0.4` pin?

### ISSUE THREAD

**Issue by ryan-williams** [rapidsai/dask-cuda#931] opened 2022-06-10 14:39 UTC
I have a project that uses `click==8.1.3` and `pip` is unhappy due to [dask-cuda's `click==8.0.4` pin](https://github.com/rapidsai/dask-cuda/blob/f93a02363d5aaf394c96fa2a57f4c0e7b586907f/requirements.txt#L6).

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 22.4.0 requires click==8.0.4, but you have click 8.1.3 which is incompatible.
```

Are there any known issues with other 8.x versions of `click`, or might e.g. `click>=8.0` suffice?

**Comment by pentschev** [comment] 2022-06-10 16:18
I believe `click>=8.0` won't suffice, as per the description from https://github.com/rapidsai/dask-cuda/pull/883 .

@charlesbluca do you know if we could make the `click` dependency less restrictive? Perhaps we may need to skip some versions, like `8.1.0`.

**Comment by ryan-williams** [comment] 2022-06-13 16:44
Thanks for the pointer. I see [#883 chose `click==8.0.4`](https://github.com/rapidsai/dask-cuda/pull/883#discussion_r838852573) based on https://github.com/rapidsai/integration/pull/453, which in turn points at https://github.com/psf/black/issues/2964, which says:

> Please use Black 22.3.0 which was just released to fix this issue or pin Click to 8.0.0, 8.0.1, 8.0.2, 8.0.3, or 8.0.4.

Possible routes forward:
- upgrade to `black>=22.3.0` here (and in other Rapids libraries?)
- upgrade to `click>8.1.0`? ([previous comment](https://github.com/rapidsai/dask-cuda/issues/931#issuecomment-1152527966) suggests the issue may be specific to `click==8.1.0` & `black<23`)
- Vendor `click`
  - Metaflow recently did this https://github.com/Netflix/metaflow/pull/929
  - Maybe more complex than it's worth, but otoh `click` is a good candidate for vendoring for exactly the reasons we're running into here: many libraries in a given dependency tree are liable to use different versions of `click`, basically at random and independently from one another

I don't think it's super urgent, just noting what I see as the options. My `click==8.1.3` project seems to work fine despite `pip` complaining about the broken 8.0.4 pin here; I'm not sure we are exercising whichever parts of this library depend on `click`.

**Comment by charlesbluca** [comment] 2022-06-13 17:01
> I see https://github.com/rapidsai/dask-cuda/pull/883#discussion_r838852573 based on https://github.com/rapidsai/integration/pull/453, which in turn points at https://github.com/psf/black/issues/2964,

IIRC, this issue was actually unrelated to the breakage in Black (though we did bump to 22.3.0 in https://github.com/rapidsai/dask-cuda/pull/889), and was because of issues with dask-cuda's CLI caused by the bump to click 8.1.0 (some additional context on this in https://github.com/rapidsai/dask-cuda/pull/883#discussion_r838852573), which in turn stemmed from issues with Distributed's CLI.

Assuming that this has been resolved on Distributed's end (and our Dask min version bumped accordingly), we should be safe to go back to the looser pinning we once used prior to #883.

**Comment by jakirkham** [comment] 2022-06-13 17:06
Believe this fixed the Distributed issue ( https://github.com/dask/distributed/pull/6018 ). Though it landed in a version of Distributed after the one we pinned to in that RAPIDS release. Should be good to relax it now

**Comment by charlesbluca** [comment] 2022-06-13 17:30
Yup, opened #932 to hopefully resolve this

**Closed** 2022-06-15 20:53 UTC
